name: Deploy Website to AWS S3

on:
  push:
    branches:
      - main  # Or your primary branch name (e.g., master)
    paths:
      - 'website/**'  # Only run if changes are made within the /website directory

  workflow_dispatch: # Allows you to trigger this workflow manually from the Actions tab in GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "ca-central-1"     
      S3_BUCKET_NAME: "sachinbulchandani-portfolio"  

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Updated to v4 for latest features

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # Updated to v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy static site to S3
        run: |
          aws s3 sync ./website s3://${{ env.S3_BUCKET_NAME }} --delete
          echo "Deployment to S3 complete."
          echo "You can access your site at: http://${{ env.S3_BUCKET_NAME }}.s3-website.${{ env.AWS_REGION }}.amazonaws.com"