name: Deploy Frontend Demo to Cloud Run

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'breast-cancer-demo/**' # Only run when files in this folder change

  workflow_dispatch: # Allows to trigger this workflow manually from the Actions tab in GitHub

env:
  PROJECT_ID: cv-cancer
  REGION: northamerica-northeast2
  # REPO_NAME: Sachin-Portfolio
  SERVICE_NAME: breast-cancer-demo-frontend
  IMAGE_NAME: breast-cancer-demo-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository (Full & Clean)
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./breast-cancer-demo
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --memory=512Mi \
            --allow-unauthenticated \
            --set-env-vars="LAST_DEPLOYMENT_SHA=${{ github.sha }}" \
            --format="value(status.url)"